kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: flow-federate-mysql
    namespace: iflearner
  data:
    my.cnf: |
      [mysqld]
      # Only allow connections from localhost
      bind-address = 0.0.0.0
      explicit_defaults_for_timestamp = 1
      #symbolic-links=0
      character-set-server=utf8
      skip-host-cache
      skip-name-resolve
      sql_mode =STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      # skip-grant-tables
      [mysql]
      default-character-set=utf8
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: flow-federate-mysql
    namespace: iflearner
  spec:
    serviceName: flow-federate-mysql
    selector:
      matchLabels:
        app: flow-federate-mysql
    replicas: 1
    template:
      metadata:
        name: flow-federate-mysql
        labels:
          app: flow-federate-mysql
      spec:
        containers:
        - image: mysql:5.7.26
          name: flow-federate-mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "flow_federate@123"
          - name: MYSQL_DATABASE
            value: flow_federate
          volumeMounts:
          - mountPath: /etc/localtime
            name: localtime
          - mountPath: /etc/hosts
            name:  hosts
          - mountPath: /var/lib/mysql
            name: pvc-volumes
            subPath: "iflearner-flow/flow-federate-voluments/mysql/data"
          - name: config
            mountPath: /etc/mysql/conf.d/my.cnf
            subPath: my.cnf
          ports:
          - containerPort: 3306
        volumes:
         - name: localtime
           hostPath:
             path: /etc/localtime
         - name: hosts
           hostPath:
             path: /etc/hosts
         - name: config
           configMap:
             name: flow-federate-mysql
         - name: pvc-volumes
           persistentVolumeClaim:
             claimName: flow-federate-pvc
- apiVersion: v1
  kind: Service
  metadata:
    name: flow-federate-mysql
    namespace: iflearner
  spec:
    type: NodePort
    ports:
    - name: http
      port: 3306
      targetPort: 3306
      nodePort: 32307
    selector:
      app: flow-federate-mysql