apiVersion: v1
kind: PersistentVolume
metadata:
  name: flow-federate-pv
  labels:
    type: flow-server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/iflearner"