apiVersion: v1
kind: PersistentVolume
metadata:
  name: flow-federate-pv
  labels:
    type: flow-server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.244.1.4 #替换为真实nfs的ip地址
    path: "/" #请根据真实情况替换