apiVersion: v1
kind: Service
metadata:
  name: iflearner_flow_server
spec:
  selector:
    app: iflearner_flow_server
  type: NodePort
  ports:
  -  port: 1235
     protocol: TCP
     targetPort: 1235
     nodePort: 32035
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iflearner_flow_server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iflearner_flow_server
  template:
    metadata:
      labels:
        app: iflearner_flow_server
    spec:
      containers:
      - name: iflearner_flow_server
        image: iflearner_flow_server:0.1
        command: ["python3", "app.py"]
        args:
        - --host 0.0.0.0
        - --port 1235
        env:
          - name: FLASK_ENV
            value: "production"
          - name: FLOW_SERVER_CONF_PATH
              value: "/data/iflearner_flow/python/iflearner_flow_server/conf/flow_server_prod.yaml"
        ports:
        - name: http
          containerPort: 1235
        volumeMounts:
          - mountPath: /etc/localtime
            name: localtime
          - mountPath: /etc/hosts
            name: hosts
          - mountPath: /data/iflearner_flow/python/iflearner_flow_server/conf/flow_server_prod.yaml
              name: conf
          - mountPath: /data/iflearner_flow/python/iflearner_flow_server/log
              name: log
          volumes:
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: hosts
              hostPath:
                path: /etc/hosts
            - name: conf
                hostPath:
                  path: ${PWD}/conf/flow_server_prod.yaml
            - name: log
                hostPath:
                  path: ${PWD}/log
