apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-server-srv
  namespace: iflearner
  labels:
    app: flow-server-srv
data:
  flow_server_prod.yml: |-
    flask:
      debug: false
    database:
      name: "flow_server"
      host: "flow-server-mysql.iflearner.svc.cluster.local"
      port: 3306
      user: "root"
      password: "flow_server@123"
      options:
        init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
      sqlalchemy_track_modifycations: false
      sqlalchemy_echo: false
      sqlalchemy_pool_size: 10
      sqlalchemy_pool_timeout: 10
      sqlalchemy_pool_overflow: 2
    flow:
      iflearner_server_image: ghcr.io/iflytek/iflearner:v0.1.0
      iflearner_server_args:
        - "python"
        - "iflearner/business/homo/aggregate_server.py"
    log:
      flow:
        level: "INFO"
        enable_file: true
        enable_console: true
        log_path: "./log/flow.log"
      sockeio:
        level: "INFO"
        enable_file: true
        enable_console: false
        log_path: "./log/socket_io.log"
      sqlengine:
        level: "INFO"
        enable_file: true
        enable_console: false
        log_path: "./log/sql_engine.log"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-server-srv
  namespace: iflearner
spec:
  selector:
    matchLabels:
      app: flow-server-srv
  template:
    metadata:
      labels:
        app: flow-server-srv
    spec:
      serviceAccountName: iflearner-operator-controller-manager
      containers:
        - name: flow-server-srv
          image: ghcr.io/iflytek/iflearner-flow-server:0.2.0
          workingDir: /data/iflearner-flow/python/iflearner_flow_server
          command:
            - python3
            - app.py
          volumeMounts:
            - name: server-config
              mountPath: /data/iflearner-flow/python/iflearner_flow_server/conf/flow_server_prod.yaml
              readOnly: true
              subPath: flow_server_prod.yml
            - mountPath: /data/iflearner-flow/python/iflearner_flow_server/log
              name: pvc-volumes
              subPath: "iflearner-flow/flow-server-voluments/iflearner_flow_server/log"
      volumes:
        - name: server-config
          configMap:
            defaultMode: 0644
            name: flow-server-srv
        - name: pvc-volumes
          persistentVolumeClaim:
            claimName: flow-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: flow-server-srv
  namespace: iflearner
spec:
  type: NodePort
  ports:
    - name: http
      port: 1235
      targetPort: 1235
      nodePort: 32235
  selector:
    app: flow-server-srv
